repos:

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        name: "General  :    Check added large files"
        args: [--maxkb=4096]
    # - id: check-json
    #   name: "General  :    Check JSON"
      - id: check-toml
        name: "General  :    Check TOML"
      - id: check-yaml
        name: "General  :    Check YAML"
      - id: trailing-whitespace
        name: "General  :    Fix Trailing whitespace"
      - id: end-of-file-fixer
        name: "General  :    Fix End of file"
  - repo: https://github.com/maresb/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
        name: "General  :    Check JSON"

  # Backend hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        name: "Backend  :    Check AST"
        files: ^backend/src/
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        name: "Backend  :    Absolufy imports"
        files: ^backend/src/
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: "Backend  :    Sort imports"
        files: ^backend/src/
        args: [--settings-path=backend/pyproject.toml]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: "Backend  :    Format code"
        files: ^backend/src/
        args: [--config=backend/pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        name: "Backend  :    Static type checking"
        files: ^backend/src/
        args: [--config-file=backend/pyproject.toml]
        additional_dependencies:
          - starlette
          - fastapi

  # Frontend hooks
  - repo: local
    hooks:
      - id: ng-lint
        name: "Frontend :    Ng-Lint"
        language: system
        pass_filenames: false
        # entry: bash -c "cd frontend && ng lint"
        entry: python -c "import os; os.chdir('frontend'); exit(os.system('ng lint --fix'))"
